web_test:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Web Tests
      run: mvn test -Dbrowser.headless=true -PwebTests

    - name: Upload Web Test Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: web_test
        path: target/web-reports
